### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by hryGithub** [llongtao/swagger-showdoc#14]
[ERROR] /root/swagger-showdoc/swagger3-showdoc-spring-boot-starter/src/main/java/top/aexp/swaggershowdoc/springboot/plug/RequiredPlugin.java:[55,104] incompatible types: java.lang.Object cannot be converted to boolean

**Comment by llongtao** [comment]
这个是你项目用的swagger版本和我用的版本不兼容, 如果能改你们项目的swagger改成一致的就行,如果不行拉到本地修改下在用吧

**Comment by hryGithub** [comment]
我只是单独编译这个工程，想以独立服务的方式运行，就报这个错

**Comment by llongtao** [comment]
只编译独立项目用这个命令,不需要spring-boot-starter模块
mvn package -pl swagger-showdoc-server -am

**Comment by hryGithub** [comment]
感谢，编译通过了
