### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by cqzaiercn** [llongtao/swagger-showdoc#15]
[ERROR] /E:/githubCode/swagger-showdoc/swagger3-showdoc-spring-boot-starter/src/main/java/top/aexp/swaggershowdoc/springboot/plug/RequiredPlugin.java:[55,104] 不兼容的类型: java.lang.Object无法转换为boolean

**Comment by llongtao** [comment]
这个问题我已经发现了,等我提交一下

**Comment by llongtao** [comment]
提交了
